name: Format Python Code with Ruff

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Run Ruff to to check, fix, and format Python code in the src/ and test/ directories
      uses: astral-sh/ruff-action@v3
      run: |
        ruff check --fix src/ test/
        ruff format src/ test/
