name: Format Python Code with Ruff

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Run Ruff to to check code style and fix issues
      uses: astral-sh/ruff-action@v3
      with:
        args: check src/ test/ --fix
    
    - name: Run Ruff to format code
      uses: astral-sh/ruff-action@v3
      with:
        args: format src/ test/

    - name: Commit changes
      run: |
        git config --global user.email "
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Format Python code with Ruff"
        git push